//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachhBharatAPI.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSEmpCodeDatail
    {
        public int ID { get; set; }
        public string UCode { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AppId { get; set; }
        public Nullable<int> CId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
