//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachhBharatAPI.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerDetail
    {
        public int pId { get; set; }
        public Nullable<int> qrEmpId { get; set; }
        public string pName { get; set; }
        public string pMobile { get; set; }
        public string pAddress { get; set; }
        public string vendorType { get; set; }
        public string wagesMode { get; set; }
        public Nullable<int> perQrPlate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> lastModifyDate { get; set; }
    }
}
